version: 1.0.{build}

cache:
  - C:\ProgramData\chocolatey\cache
  - C:\strawberry\cpan\sources

environment:
  matrix:
    - perl: "5.8.9.5"
    - perl: "5.10.1.5"
    - perl: "5.12.3.20180709"
    - perl: "5.14.4.1"
    - perl: "5.16.3.20170202"
    - perl: "5.18.4.1"
    - perl: "5.20.3.3"
    - perl: "5.22.3.1"
    - perl: "5.24.4.1"
    - perl: "5.26.3.1"
    - perl: "5.28.2.1"
    - perl: "5.30.3.1"
    - perl: "5.32.1.1"

image:
  - Visual Studio 2015

platform:
  - x86
  - x64

matrix:
  exclude:
    - platform: x64
      perl: "5.8.9.5"
    - platform: x64
      perl: "5.10.1.5"

services:
  - mysql

install:
  - git fetch -q origin %APPVEYOR_PULL_REQUEST_HEAD_COMMIT%
  - git checkout -qf %APPVEYOR_PULL_REQUEST_HEAD_COMMIT%
  - ren C:\MinGW MinGW_do_not_use
  - ren C:\Perl Perl_do_not_use
  - ren "C:\\Program Files\\Git\\usr\\bin\\perl.exe" perl.exe_do_not_use
  - if /I %PLATFORM% == x86 (set x86=--forcex86) else (set "x86= ")
  - choco config set cacheLocation C:\ProgramData\chocolatey\cache
  - cinst StrawberryPerl --version %perl% %x86% --allow-empty-checksums
  - refreshenv
  - perl -V
  - perl -e "print qq(o conf urllist push http://www.cpan.org\no conf commit\n)" | cpan
  - cpan -T App::cpanminus
  - perl "-MExtUtils::MakeMaker 6.58" -e "" || cpanm --quiet --notest ExtUtils::MakeMaker@6.58
  - perl "-MCPAN::Meta 2.112580" -e "" || cpanm --quiet --notest CPAN::Meta@2.112580
  - cpanm --quiet --notest --skip-satisfied DBI~1.608 Devel::CheckLib~1.12
  - cpanm --quiet --notest --skip-satisfied --installdeps --with-configure --with-develop --with-recommends --with-suggests .

build_script:
  - set DBD_MARIADB_TESTUSER=root
  - set DBD_MARIADB_TESTPASSWORD=Password12!
  - perl -MConfig -e "system({$Config{make}} $Config{make}, @ARGV); exit((($? >> 8) | ($? & 127)) & 255)" realclean || (exit 0)
  - perl Makefile.PL
  - perl -MConfig -e "system({$Config{make}} $Config{make}, @ARGV); exit((($? >> 8) | ($? & 127)) & 255)"

test_script:
  - set HARNESS_OPTIONS=j4
  - set RELEASE_TESTING=1
  - set CONNECTION_TESTING=1
  - perl -MConfig -e "system({$Config{make}} $Config{make}, @ARGV); exit((($? >> 8) | ($? & 127)) & 255)" test
